got opening disc to work reliably
need to update parsing the makemkv path. It should
be able to convert to the appropriate characters.

Also need to fix the error with "'" in a text component.
Error: Text string "''" must be rendered inside <Text> component